'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAdminProfile } from '@/components/admin-access-gate';
import { Dialog, Field, messageOf } from '@/components/admin-directory-ui';
import {
  normalizeTipDelete, normalizeTipImport, normalizeWritingTip, normalizeWritingTips, pendingTipOperation,
  slugifyWritingTip, tipOperationMatches, writingTipMatches, writingTipSlugPath, writingTipsFilters, writingTipsHref, writingTipsPath,
} from '@/lib/admin-writing-tips-model.mjs';

type Task = 'task_1' | 'task_2' | 'both';
type Tip = { id: string; title: string; slug: string; bodyMarkdown: string; taskType: Task; contentType: string; category: string | null; published: boolean; displayOrder: number; typeData: Record<string, unknown>; createdAt: string; updatedAt: string };
type Draft = { title: string; slug: string; bodyMarkdown: string; taskType: Task; category: string; published: boolean; displayOrder: string };
type Pending = { account: string; action: 'create' | 'update' | 'publish' | 'delete' | 'import'; id: string | null; expected: { slug: string; title: string; published: boolean | null; bodyMarkdown: string }; startedAt: string };
type ImportPreview = { contentType: string; title: string; slug: string; taskType: string; category: string | null; published: boolean; displayOrder: number; typeData: Record<string, unknown>; bodyMarkdown: string };
type Banner = { kind: 'success' | 'warning' | 'error'; title: string; detail: string };
type Snapshot = { key: string; rows: Tip[]; malformed: number; capped: boolean; readAt: string };
type LoadIssue = { key: string; message: string };
const EMPTY: Draft = { title: '', slug: '', bodyMarkdown: '', taskType: 'task_2', category: '', published: false, displayOrder: '0' };
const TASK_COPY: Record<string, string> = { task_1: 'Task 1', task_2: 'Task 2', both: 'Cả hai' };
const TYPE_COPY: Record<string, string> = { tip: 'Mẹo', knowledge: 'Kiến thức', sample: 'Bài mẫu', outline: 'Dàn bài' };
const storageKey = (account: string) => `awt-pending:${account}`;
const statusOf = (caught: unknown) => typeof caught === 'object' && caught !== null && 'status' in caught ? Number((caught as { status?: unknown }).status) : 0;
const definitive = (status: number) => status >= 400 && status < 500 && ![408, 425, 429].includes(status);
const readStored = (account: string) => { try { return pendingTipOperation(JSON.parse(sessionStorage.getItem(storageKey(account)) || 'null'), account) as Pending | null; } catch { return null; } };
const writeStored = (value: Pending) => sessionStorage.setItem(storageKey(value.account), JSON.stringify(value));
const clearStored = (account: string) => sessionStorage.removeItem(storageKey(account));
const formatTime = (value: string) => new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));

function Markdown({ value }: { value: string }) {
  const [html, setHtml] = useState('');
  useEffect(() => {
    let attempts = 0; let timer = 0; const render = () => { if (window.renderMarkdown) { setHtml(window.renderMarkdown(value)); return; } if (attempts++ < 40) timer = window.setTimeout(render, 50); };
    setHtml(''); render(); return () => window.clearTimeout(timer);
  }, [value]);
  return html ? <div className="md-body" dangerouslySetInnerHTML={{ __html: html }}/> : <pre className="awt-plain">{value}</pre>;
}

export function AdminWritingTips() {
  const profile = useAdminProfile(); const router = useRouter(); const params = useSearchParams();
  const filters = useMemo(() => writingTipsFilters({ task_type: params?.get('task_type'), published: params?.get('published'), q: params?.get('q') }), [params]);
  const filterKey = `${profile.id}|${filters.taskType}|${filters.published}`;
  const [search, setSearch] = useState(filters.q); const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [loading, setLoading] = useState(true); const [loadIssue, setLoadIssue] = useState<LoadIssue | null>(null); const [banner, setBanner] = useState<Banner | null>(null);
  const [editor, setEditor] = useState<Tip | 'new' | null>(null); const [draft, setDraft] = useState<Draft>(EMPTY); const [formError, setFormError] = useState<string | null>(null);
  const [action, setAction] = useState<{ kind: 'publish' | 'delete'; tip: Tip } | null>(null); const [importFile, setImportFile] = useState<File | null>(null); const [importPreview, setImportPreview] = useState<ImportPreview | null>(null); const [importErrors, setImportErrors] = useState<{ field: string; message: string }[]>([]); const [importError, setImportError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false); const [pending, setPending] = useState<Pending | null>(null); const lockRef = useRef(false); const pendingRef = useRef<Pending | null>(null); const accountRef = useRef(profile.id); const sequence = useRef(0); accountRef.current = profile.id;
  const current = snapshot?.key === filterKey ? snapshot : null; const rows = current?.rows || []; const malformed = current?.malformed || 0; const capped = current?.capped || false; const readAt = current?.readAt || null; const loadError = loadIssue?.key === filterKey ? loadIssue.message : null;
  const visible = useMemo(() => rows.filter((row) => writingTipMatches(row, filters)), [rows, filters]);
  const navigate = useCallback((next: Record<string, string>) => router.replace(writingTipsHref({ task_type: filters.taskType, published: filters.published, q: filters.q, ...next }), { scroll: false }), [filters, router]);

  const readList = useCallback(async (unfiltered = false) => {
    const normalized = normalizeWritingTips(await window.api.get<unknown>(writingTipsPath(filters, unfiltered)));
    if (!normalized) throw new Error('Danh sách mẹo không đúng contract.'); return normalized as { rows: Tip[]; malformedCount: number; capped: boolean };
  }, [filters.taskType, filters.published]);
  const readOne = useCallback(async (id: string) => normalizeWritingTip(await window.api.get<unknown>(`/admin/writing/tips/${encodeURIComponent(id)}`)) as Tip | null, []);
  const readBySlug = useCallback(async (slug: string) => {
    const normalized = normalizeWritingTips(await window.api.get<unknown>(writingTipSlugPath(slug)));
    if (!normalized || normalized.malformedCount || normalized.rows.length > 1) throw new Error('Slug readback không đúng contract hoặc không còn unique.');
    return normalized.rows[0] as Tip | undefined;
  }, []);
  const load = useCallback(async (preserve = true) => {
    const account = profile.id; const key = filterKey; const request = ++sequence.current; setLoading(true);
    try { const data = await readList(); if (request !== sequence.current || accountRef.current !== account) return null; setSnapshot({ key, rows: data.rows, malformed: data.malformedCount, capped: data.capped, readAt: new Date().toISOString() }); setLoadIssue(null); return data; }
    catch (caught) { if (request === sequence.current && accountRef.current === account) setLoadIssue({ key, message: `${preserve && current ? 'Không thể làm mới — đang giữ snapshot trước. ' : ''}${messageOf(caught)}` }); return null; }
    finally { if (request === sequence.current && accountRef.current === account) setLoading(false); }
  }, [current, filterKey, profile.id, readList]);

  const finishPending = useCallback(() => { clearStored(profile.id); pendingRef.current = null; setPending(null); }, [profile.id]);
  const reconcile = useCallback(async (operation: Pending, announce = true) => {
    if (announce) setBanner({ kind: 'warning', title: 'Đang đối chiếu thao tác', detail: 'Chỉ GET canonical state; không gửi lại mutation.' });
    pendingRef.current = operation; setPending(operation); lockRef.current = true; setBusy(true);
    try {
      let tip: Tip | null = null; let missing = false;
      if (operation.id) { try { tip = await readOne(operation.id); if (!tip) throw new Error('Tip readback sai contract.'); } catch (caught) { if (statusOf(caught) === 404) missing = true; else throw caught; } }
      else { tip = await readBySlug(operation.expected.slug) || null; missing = !tip; }
      if (accountRef.current !== operation.account) return false;
      if (operation.action === 'delete') { if (!missing) throw new Error('Canonical state vẫn còn nội dung cần xóa.'); finishPending(); setAction(null); await load(); setBanner({ kind: 'success', title: 'Đã xác nhận xóa', detail: 'Nội dung không còn trong kho canonical.' }); return true; }
      if (!tipOperationMatches(operation, tip)) throw new Error('Canonical state chưa khớp thao tác đang chờ.');
      finishPending(); setAction(null); setEditor(null); setImportFile(null); setImportPreview(null); setImportErrors([]); await load();
      setBanner({ kind: 'success', title: 'Đã đối chiếu từ máy chủ', detail: operation.action === 'publish' ? 'Trạng thái hiển thị cho học viên đã được xác nhận.' : operation.action === 'import' ? 'Nội dung import đã được xác nhận theo slug.' : 'Nội dung đã được lưu đúng canonical state.' }); return true;
    } catch (caught) { if (accountRef.current === operation.account) setBanner({ kind: 'error', title: 'Chưa đối chiếu được thao tác', detail: `${messageOf(caught)} Không lặp lại mutation; dùng “Đối chiếu lại”.` }); return false; }
    finally { if (accountRef.current === operation.account) { lockRef.current = false; setBusy(false); } }
  }, [finishPending, load, readBySlug, readOne]);

  useEffect(() => { setSearch(filters.q); setBanner(null); const stored = readStored(profile.id); pendingRef.current = stored; lockRef.current = Boolean(stored); setPending(stored); setBusy(Boolean(stored)); if (stored) void reconcile(stored, false).then((confirmed) => { if (!confirmed) void load(false); }); else void load(false); return () => { sequence.current += 1; }; }, [profile.id, filters.taskType, filters.published]); // eslint-disable-line react-hooks/exhaustive-deps

  const begin = (operation: Pending) => { pendingRef.current = operation; writeStored(operation); setPending(operation); lockRef.current = true; setBusy(true); setBanner(null); };
  const rejected = () => { finishPending(); lockRef.current = false; setBusy(false); };
  const openEditor = (tip: Tip | null) => { setEditor(tip || 'new'); setDraft(tip ? { title: tip.title, slug: tip.slug, bodyMarkdown: tip.bodyMarkdown, taskType: tip.taskType, category: tip.category || '', published: tip.published, displayOrder: String(tip.displayOrder) } : { ...EMPTY }); setFormError(null); };
  const save = async () => {
    if (lockRef.current || pendingRef.current) return; const title = draft.title.trim(); const bodyMarkdown = draft.bodyMarkdown.trim(); const slug = draft.slug.trim() || slugifyWritingTip(title); const displayOrder = Number(draft.displayOrder);
    if (title.length < 2) return setFormError('Tiêu đề phải có ít nhất 2 ký tự.'); if (!bodyMarkdown) return setFormError('Nội dung Markdown không được để trống.'); if (!Number.isInteger(displayOrder) || displayOrder < 0 || displayOrder > 100000) return setFormError('Thứ tự phải là số nguyên từ 0 đến 100000.');
    const editing = editor !== 'new' && editor; const operation: Pending = { account: profile.id, action: editing ? 'update' : 'create', id: editing ? editing.id : null, expected: { slug, title, published: draft.published, bodyMarkdown }, startedAt: new Date().toISOString() }; begin(operation); setFormError(null);
    try { const payload = { title, slug, body_markdown: bodyMarkdown, task_type: draft.taskType, category: draft.category.trim() || null, published: draft.published, display_order: displayOrder }; const raw = editing ? await window.api.patch<unknown>(`/admin/writing/tips/${encodeURIComponent(editing.id)}`, payload) : await window.api.post<unknown>('/admin/writing/tips', payload); const ack = normalizeWritingTip(raw) as Tip | null; if (!ack || (editing && ack.id !== editing.id) || ack.slug !== slug) throw new Error('ACK lưu nội dung không khớp identity.'); operation.id = ack.id; writeStored(operation); setPending(operation); await reconcile(operation, false); }
    catch (caught) { if (accountRef.current !== operation.account) return; const status = statusOf(caught); if (definitive(status)) { rejected(); setFormError(messageOf(caught)); } else await reconcile(operation, false); }
  };
  const runAction = async () => {
    if (!action || lockRef.current || pendingRef.current) return; const tip = action.tip; const operation: Pending = { account: profile.id, action: action.kind, id: tip.id, expected: { slug: tip.slug, title: tip.title, published: action.kind === 'publish' ? !tip.published : null, bodyMarkdown: action.kind === 'publish' ? tip.bodyMarkdown : '' }, startedAt: new Date().toISOString() }; begin(operation);
    try { if (action.kind === 'publish') { const ack = normalizeWritingTip(await window.api.patch<unknown>(`/admin/writing/tips/${encodeURIComponent(tip.id)}`, { published: !tip.published })) as Tip | null; if (!ack || ack.id !== tip.id || ack.published === tip.published) throw new Error('ACK publish không khớp trạng thái.'); } else { if (!normalizeTipDelete(await window.api.delete<unknown>(`/admin/writing/tips/${encodeURIComponent(tip.id)}`), tip.id)) throw new Error('ACK xóa không khớp identity.'); } await reconcile(operation, false); }
    catch (caught) { if (accountRef.current !== operation.account) return; const status = statusOf(caught); if (definitive(status) && !(action.kind === 'delete' && status === 404)) { rejected(); setBanner({ kind: 'error', title: 'Thao tác bị từ chối', detail: messageOf(caught) }); } else await reconcile(operation, false); }
  };
  const dryRun = async (file: File) => { if (lockRef.current || pendingRef.current) return; setImportFile(file); setImportError(null); setImportPreview(null); setImportErrors([]); lockRef.current = true; setBusy(true); try { const fd = new FormData(); fd.append('file', file); const data = normalizeTipImport(await window.api.upload<unknown>('/admin/writing/content/import?dry_run=true', fd)); if (!data?.dryRun) throw new Error('Dry-run import không đúng contract.'); setImportPreview(data.preview as ImportPreview | null); setImportErrors(data.errors); } catch (caught) { setImportError(messageOf(caught)); } finally { lockRef.current = false; setBusy(false); } };
  const commitImport = async () => {
    if (!importFile || !importPreview || importErrors.length || lockRef.current || pendingRef.current) return; const operation: Pending = { account: profile.id, action: 'import', id: null, expected: { slug: importPreview.slug, title: importPreview.title, published: importPreview.published, bodyMarkdown: importPreview.bodyMarkdown }, startedAt: new Date().toISOString() }; begin(operation); setImportError(null);
    try { const fd = new FormData(); fd.append('file', importFile); const data = normalizeTipImport(await window.api.upload<unknown>('/admin/writing/content/import?dry_run=false', fd)); if (!data || data.dryRun) throw new Error('ACK import commit không đúng contract.'); if (data.errors.length) { rejected(); setImportErrors(data.errors); setImportError('File không còn hợp lệ khi kiểm tra lại; chưa ghi dữ liệu.'); return; } if (!data.committedId) throw new Error('ACK import commit thiếu identity.'); operation.id = data.committedId; writeStored(operation); setPending(operation); await reconcile(operation, false); }
    catch (caught) { if (accountRef.current !== operation.account) return; const status = statusOf(caught); if (definitive(status)) { rejected(); setImportError(messageOf(caught)); } else await reconcile(operation, false); }
  };

  return <main className="awt-shell">
    <header className="awt-hero"><div><p className="awt-eyebrow">Writing · Content library</p><h1>Mẹo viết</h1><p>Biên tập nội dung Markdown, kiểm soát trạng thái xuất bản và import theo quy trình preview trước khi ghi.</p></div><div className="awt-hero__actions"><a className="adm-btn-secondary" href="/admin/writing">Writing workspace</a><button className="adm-btn-primary" type="button" onClick={() => openEditor(null)} disabled={Boolean(pending)}>Thêm nội dung</button></div></header>
    <section className="awt-overview" aria-label="Tổng quan thư viện"><div><span>Đang hiển thị</span><strong>{visible.length}</strong><small>theo bộ lọc hiện tại</small></div><div><span>Đã publish</span><strong>{rows.filter((row) => row.published).length}</strong><small>học viên có thể đọc</small></div><div><span>Bản nháp</span><strong>{rows.filter((row) => !row.published).length}</strong><small>chỉ admin nhìn thấy</small></div><div><span>Contract</span><strong>{malformed}</strong><small>dòng bị loại</small></div></section>
    {banner && <div className={`awt-banner is-${banner.kind}`} role={banner.kind === 'error' ? 'alert' : 'status'}><div><strong>{banner.title}</strong><span>{banner.detail}</span></div>{pending && <button className="adm-btn-secondary adm-btn-sm" type="button" onClick={() => void reconcile(pending)} disabled={busy}>{busy ? 'Đang đọc lại…' : 'Đối chiếu lại'}</button>}</div>}
    {loadError && <div className="awt-banner is-warning" role="alert"><div><strong>{current ? 'Đang giữ snapshot cũ' : 'Không tải được thư viện'}</strong><span>{loadError}{readAt ? ` · đọc lúc ${formatTime(readAt)}` : ''}</span></div><button className="adm-btn-secondary adm-btn-sm" type="button" onClick={() => void load()} disabled={loading}>Thử lại</button></div>}
    {(malformed > 0 || capped) && <div className="awt-banner is-warning"><strong>Dữ liệu cần chú ý</strong><span>{malformed ? `${malformed} dòng sai contract bị loại. ` : ''}{capped ? 'Kết quả đã chạm giới hạn 500 dòng.' : ''}</span></div>}
    <section className="awt-import"><div><p className="awt-eyebrow">Import có kiểm soát</p><h2>Markdown + YAML frontmatter</h2><p>Dry-run để kiểm tra metadata và xem trước nội dung; commit chỉ mở khi file hợp lệ.</p></div><label className="awt-drop"><input type="file" accept=".md,.markdown,text/markdown" disabled={busy || Boolean(pending)} onChange={(event) => { const file = event.target.files?.[0]; if (file) void dryRun(file); }}/><strong>{importFile ? importFile.name : 'Chọn file .md'}</strong><span>Kéo thả vào trình duyệt hoặc chọn từ máy</span></label>{importError && <div className="awt-inline-error" role="alert">{importError}</div>}{importPreview && <div className="awt-import__preview"><div className="awt-import__meta"><span>{TYPE_COPY[importPreview.contentType] || importPreview.contentType}</span><span>{TASK_COPY[importPreview.taskType] || importPreview.taskType}</span><span>{importPreview.published ? 'Sẽ publish' : 'Sẽ lưu nháp'}</span></div><h3>{importPreview.title || 'Thiếu tiêu đề'}</h3><code>{importPreview.slug || 'thiếu-slug'}</code>{importErrors.length ? <ul className="awt-errors">{importErrors.map((error, index) => <li key={`${error.field}-${index}`}><strong>{error.field}</strong>: {error.message}</li>)}</ul> : <Markdown value={importPreview.bodyMarkdown}/>}<div className="awt-import__actions"><button className="adm-btn-secondary" type="button" onClick={() => { setImportFile(null); setImportPreview(null); setImportErrors([]); setImportError(null); }} disabled={busy}>Xóa preview</button><button className="adm-btn-primary" type="button" onClick={() => void commitImport()} disabled={busy || Boolean(importErrors.length) || Boolean(pending)}>Lưu vào thư viện</button></div></div>}</section>
    <section className="awt-controls"><label><span>Task</span><select value={filters.taskType} onChange={(event) => navigate({ task_type: event.target.value, q: filters.q })} disabled={Boolean(pending)}><option value="">Tất cả</option><option value="task_1">Task 1</option><option value="task_2">Task 2</option><option value="both">Cả hai</option></select></label><label><span>Trạng thái</span><select value={filters.published} onChange={(event) => navigate({ published: event.target.value, q: filters.q })} disabled={Boolean(pending)}><option value="">Tất cả</option><option value="true">Đã publish</option><option value="false">Bản nháp</option></select></label><form onSubmit={(event) => { event.preventDefault(); navigate({ q: search }); }}><label htmlFor="awt-search">Tìm nội dung</label><div><input id="awt-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tiêu đề, slug, category…"/><button className="adm-btn-secondary" type="submit">Tìm</button></div></form><button className="adm-btn-secondary" type="button" onClick={() => void load()} disabled={loading}>{loading ? 'Đang làm mới…' : 'Làm mới canonical'}</button></section>
    <section className="awt-library"><header><div><p className="awt-eyebrow">Canonical content</p><h2>Thư viện biên tập</h2><p>Thứ tự hiển thị tăng dần; thay đổi chỉ báo thành công sau readback.</p></div><strong>{visible.length} mục</strong></header>{!current ? <div className="awt-state" role="status"><span className="awt-spinner"/><strong>{loading ? 'Đang đọc thư viện…' : 'Chưa có snapshot cho bộ lọc này'}</strong></div> : !visible.length ? <div className="awt-state"><strong>Không có nội dung phù hợp</strong><p>Thử đổi bộ lọc hoặc tạo mục mới.</p></div> : <div className="awt-grid">{visible.map((tip) => <article className="awt-card" key={tip.id}><div className="awt-card__meta"><span>{TASK_COPY[tip.taskType]}</span><span>{TYPE_COPY[tip.contentType] || tip.contentType}</span><span className={tip.published ? 'is-live' : 'is-draft'}>{tip.published ? 'Đã publish' : 'Bản nháp'}</span></div><h3>{tip.title}</h3><code>{tip.slug}</code><p>{tip.bodyMarkdown.replace(/[#*_>`\[\]-]/g, ' ').replace(/\s+/g, ' ').slice(0, 190)}</p><dl><div><dt>Category</dt><dd>{tip.category || '—'}</dd></div><div><dt>Thứ tự</dt><dd>{tip.displayOrder}</dd></div><div><dt>Cập nhật</dt><dd>{formatTime(tip.updatedAt)}</dd></div></dl><footer><button className="adm-btn-secondary adm-btn-sm" type="button" onClick={() => setAction({ kind: 'publish', tip })} disabled={Boolean(pending)}>{tip.published ? 'Ẩn khỏi học viên' : 'Publish'}</button><button className="adm-btn-secondary adm-btn-sm" type="button" onClick={() => openEditor(tip)} disabled={Boolean(pending)}>Sửa</button><button className="adm-btn-danger adm-btn-sm" type="button" onClick={() => setAction({ kind: 'delete', tip })} disabled={Boolean(pending)}>Xóa</button></footer></article>)}</div>}</section>
    <Dialog open={editor !== null} title={editor === 'new' ? 'Tạo nội dung mới' : 'Sửa nội dung'} description="Markdown là nguồn nội dung canonical; preview luôn đi qua bộ sanitizer dùng chung." onClose={() => setEditor(null)} busy={busy} panelClassName="awt-dialog-wide" actions={<><button className="adm-btn-secondary" type="button" onClick={() => setEditor(null)} disabled={busy}>Hủy</button><button className="adm-btn-primary" type="button" onClick={() => void save()} disabled={busy || Boolean(pending)}>{busy ? 'Đang đối chiếu…' : 'Lưu & đối chiếu'}</button></>}><div className="awt-form"><Field label="Tiêu đề"><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })}/></Field><div className="awt-form__grid"><Field label="Task"><select value={draft.taskType} onChange={(event) => setDraft({ ...draft, taskType: event.target.value as Task })}><option value="task_1">Task 1</option><option value="task_2">Task 2</option><option value="both">Cả hai</option></select></Field><Field label="Category"><input value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })}/></Field><Field label="Slug" hint="Để trống để sinh từ tiêu đề"><input value={draft.slug} onChange={(event) => setDraft({ ...draft, slug: event.target.value })}/></Field><Field label="Thứ tự"><input type="number" min="0" max="100000" value={draft.displayOrder} onChange={(event) => setDraft({ ...draft, displayOrder: event.target.value })}/></Field></div><label className="awt-toggle"><input type="checkbox" checked={draft.published} onChange={(event) => setDraft({ ...draft, published: event.target.checked })}/><span>Publish cho học viên ngay sau khi lưu</span></label><div className="awt-editor"><Field label="Nội dung Markdown"><textarea rows={18} value={draft.bodyMarkdown} onChange={(event) => setDraft({ ...draft, bodyMarkdown: event.target.value })}/></Field><div><strong>Preview đã khử độc</strong><Markdown value={draft.bodyMarkdown}/></div></div>{formError && <div className="awt-inline-error" role="alert">{formError}</div>}</div></Dialog>
    <Dialog open={action !== null} title={action?.kind === 'delete' ? 'Xóa vĩnh viễn nội dung?' : action?.tip.published ? 'Ẩn nội dung khỏi học viên?' : 'Publish nội dung cho học viên?'} description={action?.kind === 'delete' ? 'Hard delete không thể hoàn tác. Hãy chắc chắn nội dung không còn cần cho lịch sử vận hành.' : 'Trạng thái phía học viên chỉ được kết luận sau canonical readback.'} onClose={() => setAction(null)} busy={busy} actions={<><button className="adm-btn-secondary" type="button" onClick={() => setAction(null)} disabled={busy}>Hủy</button><button className={action?.kind === 'delete' ? 'adm-btn-danger' : 'adm-btn-primary'} type="button" onClick={() => void runAction()} disabled={busy || Boolean(pending)}>{busy ? 'Đang đối chiếu…' : action?.kind === 'delete' ? 'Xóa vĩnh viễn' : 'Xác nhận thay đổi'}</button></>}/>
  </main>;
}
