-- Migration: 053_d1_questions_mcq_options.sql
-- Sprint 10.5 Phase 2 — MCQ format for personalized D1 questions.
--
-- Phase 1 spec assumed free-text fill-blank. Quality inspection of 10
-- random Phase 1 generations revealed two issues with the free-text path:
--   1. AI sometimes generates ungrammatical sentences forcing the target
--      form ("she felt completely rejuvenate" instead of "rejuvenated").
--   2. acceptable_variants coverage was incomplete — verb inflections
--      and morphological variants slipped through.
--
-- Andy locked Option A (MCQ format) for Phase 2:
--   * Sidesteps grammar issue: user selects from buttons, doesn't type.
--   * Sidesteps variant coverage: validation is exact-option match.
--   * Matches the actual current d1-exercise.js UX (MCQ via options
--     array + local-grade) — Phase 1 spec's "match current UX" claim
--     was ambiguous; Phase 2 corrects course based on production reality.
--
-- Schema change: add an `options` JSONB column to user_d1_questions.
-- options[] is an array of 4 strings — the canonical target_answer
-- plus 3 distractors generated by Claude Haiku. Pre-shuffled at INSERT
-- time using a deterministic Random(question_uuid) seed so the same
-- question always presents options in the same order (allows future
-- client-side caching).
--
-- target_answer stays canonical (server-side validation source of
-- truth). Bookkeeping for free-text mode (acceptable_variants, hint,
-- blank_position_start/_end) stays — if a future "recall mode" toggle
-- ships, the same row can serve either format.
--
-- Idempotent: IF NOT EXISTS on the column. Existing 48 Phase 1 rows
-- come in with options=[] (default) — Phase 2 backfill
-- (scripts/backfill_d1_questions_mcq.py) walks them and fills options.

ALTER TABLE user_d1_questions
    ADD COLUMN IF NOT EXISTS options JSONB NOT NULL DEFAULT '[]'::jsonb;

COMMENT ON COLUMN user_d1_questions.options IS
    'Sprint 10.5 Phase 2 — MCQ format: JSONB array of 4 option strings, '
    'pre-shuffled at generation time. target_answer is one of the four '
    '(server-side check on submit). Empty array means Phase 2 backfill '
    'hasn''t run yet for this row.';
