-- Migration: 067_listening_tests_audio.sql
-- Sprint 13.4.3 — Cambridge IELTS test bundle audio fields. Supports
-- two parallel audio modes per Andy's 2026-05-21 Path 3 lock:
--   1. full_premixed         — Andy uploads 1 pre-mixed 30-min audio
--                              (instructions + pauses + halfway break
--                              all baked in by Andy)
--   2. parts_auto_assembled  — Andy uploads 4 clean section audios;
--                              server renders narrator intros via
--                              ElevenLabs + pydub-concatenates pauses
--                              into a single assembled MP3
--   3. parts_only            — 4 part audios stored without assembly
--                              (Sprint 13.6 exercise cutter source;
--                              cannot publish to students)
-- Forward-only.

ALTER TABLE listening_tests
    ADD COLUMN IF NOT EXISTS full_audio_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS full_audio_duration_seconds INTEGER
        CHECK (full_audio_duration_seconds IS NULL OR full_audio_duration_seconds > 0),
    ADD COLUMN IF NOT EXISTS full_audio_size_bytes INTEGER
        CHECK (full_audio_size_bytes IS NULL OR full_audio_size_bytes > 0),
    ADD COLUMN IF NOT EXISTS cue_points JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS audio_assembly_mode TEXT
        CHECK (audio_assembly_mode IN (
            'full_premixed', 'parts_auto_assembled', 'parts_only'
        )),
    ADD COLUMN IF NOT EXISTS assembled_audio_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS assembled_audio_generated_at TIMESTAMP WITH TIME ZONE;

COMMENT ON COLUMN listening_tests.full_audio_storage_path IS
    'Andy-uploaded pre-mixed 30-min full audio. NULL if Andy is using '
    'parts mode only. Storage path is bucket-relative; signed URL is '
    'minted on read.';
COMMENT ON COLUMN listening_tests.cue_points IS
    'Array of cue point objects shaped {type, section_num, timestamp_seconds}. '
    'Auto-generated by the assembly endpoint when mode=parts_auto_assembled. '
    'Used by Sprint 13.5 student player to highlight current section + '
    'render the pre-read pause UI.';
COMMENT ON COLUMN listening_tests.audio_assembly_mode IS
    'full_premixed       = Andy uploads 1 full audio (no server assembly). '
    'parts_auto_assembled = Andy uploads 4 parts; server renders narrator '
    '                       intros + concatenates pauses; result lives in '
    '                       assembled_audio_storage_path. '
    'parts_only          = 4 parts only; cannot publish (Sprint 13.6 cutter '
    '                       source).';
COMMENT ON COLUMN listening_tests.assembled_audio_storage_path IS
    'Web-generated assembled 30-min audio (mode=parts_auto_assembled only). '
    'Cached server-side; regenerated on demand when any part audio updates '
    '(assembled_audio_generated_at < listening_content.updated_at).';
COMMENT ON COLUMN listening_tests.assembled_audio_generated_at IS
    'When the assembled audio was last regenerated. Compared against the '
    'max updated_at of the 4 section content rows to decide whether the '
    'assembly endpoint can short-circuit (idempotent re-render).';
