import type { ClassAssignment } from './admin-class-homework-types';

export type SubmissionAssignment = Pick<ClassAssignment, 'id' | 'title' | 'skill' | 'status' | 'due_at' | 'content_id'>;
export type SubmissionStudent = { studentId: string | null; userId: string | null; name: string; hasWriting: boolean };

export type SubmissionFlag = { code: string; severity: string; label: string; why: string; action: string };
export type MissingSection = { key: string; label: string };
export type TallyStudent = { student_id: string; name: string; student_code: string | null; status: string; submitted_at: string | null; score: number | null; flags: SubmissionFlag[]; flag_level: string | null; passed_at: string | null; course_state: string | null; next_action: string | null; pass_pct: number | null; near_pass_pct: number | null; sections_done: number; sections_total: number; missing_sections: MissingSection[]; retakes: number; verdicts: number; artifact_kind: string | null; artifact_id: string | null; has_writing: boolean; writing_expected: boolean };
export type TallyPayload = { assignment: { id: string; title: string; skill: string; due_at: string | null }; sealed: boolean; homework_stale: boolean; sections_shape_unknown: boolean; writing_total: number; students: TallyStudent[]; counts: { total: number; submitted: number; late: number; missing: number; no_account: number; flagged: number; passed: number; near_pass: number; retry_full: number; in_progress: number; untouched: number } };
export type SectionResult = { key: string; label: string; pct: number | null; duration_sec: number; carried: boolean };
export type EffortStudent = { student_id: string | null; user_id: string | null; state: string; wrote: boolean; stages_done: number; minutes: number | null; questions: number; correct: number; accuracy: number | null; median_sec: number | null; idle_sec: number; last_at: string | null; attempts: number; combined_pct: number | null; next_action: string | null; pass_pct: number | null; near_pass_pct: number | null; sections_done: number; sections_total: number; section_results: SectionResult[]; missing_sections: MissingSection[]; flags: SubmissionFlag[]; attempt_minutes: number; current_attempt_minutes: number };
export type EffortPayload = { stale: boolean; stages_total: number; writing_total: number; students: EffortStudent[]; axes: { axis: string; wrong: number; attempted: number; wrong_rate: number | null; affected_students: number; student_sample: number; affected_rate: number | null; median_sec: number | null; scope: string; sample_low: boolean }[] };
export type ReportQuestion = { qid: string | null; item_key: string; prompt: string; picked: number | null; picked_text: string | null; answer: number | null; answer_text: string | null; is_correct: boolean; why_wrong: string | null; explain: string | null; seconds: number | null };
export type StudentReport = { stale: boolean; locked: boolean; threshold: number | null; totals: { answered: number; correct: number; median_sec: number | null; active_sec: number | null; idle_sec: number | null; bank_title: string | null; scope: string }; summary: { pass_pct: number | null; near_pass_pct: number | null; latest_pct: number | null; latest_action: string | null; latest_attempt_number: number | null; baseline_quiz_pct: number | null; baseline_correct: number; baseline_answered: number; latest_sections: SectionResult[] }; history: { number: number; phase: string; session_count: number; pct: number | null; next_action: string; at: string | null; completed: boolean; duration_sec: number; sections: SectionResult[] }[]; questions: ReportQuestion[] };
export type WritingPayload = { student: { id: string; name: string; code: string | null }; assignment: { id: string; title: string }; submission: null | { clean: number; total: number; model: string | null; graded_at: string | null; items: Record<string, unknown>[] } };
export type SubmissionWorkspaceProps = { cohortId: string; assignment: SubmissionAssignment; initialStudent?: SubmissionStudent | null; backLabel?: string; memberNames: Record<string, string>; memberUserIds: Record<string, string | null>; memberNamesAvailable: boolean; onBack: () => void; onMutation: () => void | Promise<void> };
