import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  normalizeTipDelete, normalizeTipImport, normalizeWritingTip, normalizeWritingTips, pendingTipOperation,
  slugifyWritingTip, tipOperationMatches, writingTipMatches, writingTipSlugPath, writingTipsFilters, writingTipsHref, writingTipsPath,
} from '../lib/admin-writing-tips-model.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..'); const read = (...parts) => readFileSync(join(ROOT, ...parts), 'utf8');
const PAGE = read('app', '(authed-admin-writing-tips)', 'admin', 'writing', 'tips', 'page.tsx'); const COMPONENT = read('app', '(authed-admin-writing-tips)', 'admin', 'writing', 'tips', 'admin-writing-tips.tsx'); const LAYOUT = read('app', '(authed-admin-writing-tips)', 'layout.tsx'); const CSS = read('public', 'css', 'admin-writing-tips-next.css');
const CONFIG = read('next.config.ts'); const CHROME = read('public', 'js', 'components', 'aver-admin-chrome.js'); const HUB = read('app', '(authed-admin-writing)', 'admin', 'writing', 'page.tsx'); const LEDGER = read('..', 'docs', 'ROUTE_LEDGER.md'); const WORKFLOW = read('..', '.github', 'workflows', 'parity-gate.yml');
const raw = { id: 't1', title: '<img onerror=x>', slug: 'intro-task-2', body_markdown: '# Body', task_type: 'task_2', content_type: 'tip', category: 'ideas', published: false, display_order: 3, type_data: {}, created_at: '2026-08-13T00:00:00Z', updated_at: '2026-08-13T00:00:00Z' };

describe('Admin Writing Tips native model', () => {
  test('normalizes strict rows and reports malformed/duplicate data', () => { const list = normalizeWritingTips({ tips: [raw, raw, { bad: true }] }); assert.equal(list.rows.length, 1); assert.equal(list.malformedCount, 2); assert.equal(list.rows[0].title, '<img onerror=x>'); assert.equal(normalizeWritingTips([]), null); assert.equal(normalizeWritingTip({ ...raw, task_type: 'task2' }), null); });
  test('pins filters, canonical URLs and local search', () => { assert.deepEqual(writingTipsFilters({ task_type: 'bad', published: 'true', q: ' intro ' }), { taskType: '', published: 'true', q: 'intro' }); assert.equal(writingTipsHref({ task_type: 'task_2', published: 'false', q: 'ideas' }), '/admin/writing/tips?task_type=task_2&published=false&q=ideas'); assert.equal(writingTipsPath({ taskType: 'task_1', published: 'true' }), '/admin/writing/tips?limit=500&task_type=task_1&published=true'); assert.equal(writingTipSlugPath('receipt tip'), '/admin/writing/tips?slug=receipt+tip&limit=2'); assert.ok(writingTipMatches(normalizeWritingTip(raw), { q: 'IDEAS' })); });
  test('matches every persisted field before clearing a receipt', () => { assert.equal(slugifyWritingTip('Đề mẫu Task 2'), 'de-mau-task-2'); assert.deepEqual(normalizeTipDelete({ message: 'ok', tip_id: 't1' }, 't1'), { id: 't1' }); assert.equal(normalizeTipDelete({ message: 'ok', tip_id: 't2' }, 't1'), null); const imported = normalizeTipImport({ parsed_data: { content_type: 'tip', title: 'T', slug: 't', task_type: 'both', body_markdown: 'B' }, validation_errors: [], dry_run: true, committed_id: null, action: null }); assert.equal(imported.preview.slug, 't'); const pending = { account: 'a1', action: 'create', id: null, expected: { slug: 'intro-task-2', title: '<img onerror=x>', published: false, bodyMarkdown: '# Body', taskType: 'task_2', contentType: 'tip', category: 'ideas', displayOrder: 3, typeData: {} }, startedAt: '2026-08-13T00:00:00Z' }; const op = pendingTipOperation(pending, 'a1'); assert.ok(tipOperationMatches(op, normalizeWritingTip(raw))); for (const changed of [{ task_type: 'both' }, { category: 'other' }, { display_order: 4 }, { content_type: 'knowledge' }, { type_data: { band: 7 } }]) assert.equal(tipOperationMatches(op, normalizeWritingTip({ ...raw, ...changed })), false); assert.equal(pendingTipOperation(pending, 'a2'), null); });
});

describe('/admin/writing/tips native ownership and safety', () => {
  test('owns clean route and preserves direct legacy rollback', () => { assert.match(PAGE, /AdminWritingTipsPage/); assert.match(PAGE, /<AdminAccessGate>/); assert.doesNotMatch(CONFIG, /source:\s*['"]\/admin\/writing\/tips['"]/); assert.ok(existsSync(join(ROOT, 'public', 'pages', 'admin', 'writing', 'tips.html'))); assert.match(CHROME, /slug:\s*'tips'[^\n]+href:\s*'\/admin\/writing\/tips'/); assert.match(HUB, /Mẹo viết[^\n]+NATIVE/); assert.match(LEDGER, /`\/admin\/writing\/tips`[^\n]+authed-admin-writing-tips[^\n]+native React ownership/); });
  test('uses bounded canonical readback, account receipt and never browser confirm', () => { for (const token of ['awt-pending:', 'readOne(operation.id)', 'readBySlug(operation.expected.slug)', 'writingTipSlugPath', 'tipOperationMatches', 'normalizeTipImport', 'dry_run=true', 'dry_run=false', 'Không lặp lại mutation', 'File không còn hợp lệ khi kiểm tra lại; chưa ghi dữ liệu.']) assert.ok(COMPONENT.includes(token), token); assert.match(COMPONENT, /pendingRef\.current/); assert.match(COMPONENT, /lockRef\.current = Boolean\(stored\)/); assert.match(COMPONENT, /definitive\(status\)/); assert.match(COMPONENT, /accountRef\.current !== operation\.account/); assert.match(COMPONENT, /accountRef\.current === operation\.account/); assert.doesNotMatch(COMPONENT, /window\.confirm|window\.alert|\bconfirm\(/); });
  test('keys every visible server snapshot by admin account and server-side filters', () => { assert.match(COMPONENT, /const filterKey = `\$\{profile\.id\}\|\$\{filters\.taskType\}\|\$\{filters\.published\}`/); assert.match(COMPONENT, /snapshot\?\.key === filterKey/); assert.match(COMPONENT, /setSnapshot\(\{ key, rows:/); assert.match(COMPONENT, /loadIssue\?\.key === filterKey/); });
  test('loads shared sanitizer and governed responsive interaction', () => { assert.match(LAYOUT, /marked@12\.0\.2/); assert.match(LAYOUT, /dompurify@3\.4\.8/); assert.match(LAYOUT, /\/js\/markdown\.js/); for (const style of ['admin-components.css', 'admin-buttons.css', 'admin-status.css', 'markdown.css', 'admin-writing-tips-next.css']) assert.ok(LAYOUT.includes(style)); assert.match(CSS, /\.awt-shell>\*\{min-width:0\}/); assert.match(CSS, /min-height:44px/); assert.match(CSS, /@media\(max-width:720px\)/); assert.match(CSS, /@media\(max-width:430px\)/); assert.match(CSS, /:focus-visible/); assert.match(CSS, /@media\(prefers-reduced-motion:reduce\)/); for (const dependency of ["backend/routers/admin_writing_tips.py", "frontend/app/(authed-admin-writing-tips)/**", 'frontend/public/css/admin-writing-tips-next.css', 'verify-admin-writing-tips-flow.mjs']) assert.ok(WORKFLOW.includes(dependency), dependency); });
});
