import { describe, test } from 'node:test'; import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs'; import { dirname, join } from 'node:path'; import { fileURLToPath } from 'node:url';
import { formatGrammarMatchScore, normalizeGrammarRecommendPayload } from '../lib/admin-grammar-recommend-model.mjs';
const ROOT=join(dirname(fileURLToPath(import.meta.url)),'..'); const read=(...p)=>readFileSync(join(ROOT,...p),'utf8');
const PAGE=read('app','(authed-admin-grammar-recommend)','admin','grammar','recommend-test','page.tsx'); const CLIENT=read('app','(authed-admin-grammar-recommend)','admin','grammar','recommend-test','admin-grammar-recommend.tsx'); const CSS=read('public','css','admin-grammar-recommend-next.css'); const HUB=read('app','(authed-admin-grammar)','admin','grammar','page.tsx'); const CHROME=read('public','js','components','aver-admin-chrome.js'); const LEGACY=read('public','js','admin-grammar-recommend.js'); const WORKFLOW=read('..','.github','workflows','parity-gate.yml'); const LEDGER=read('..','docs','ROUTE_LEDGER.md');
const c={slug:'past-perfect',category:'tenses',title:'Past Perfect',url:'/grammar/tenses/past-perfect#use',status:'complete',score:.91,summary:'Summary',anchor:'use'};
describe('/admin/grammar/recommend-test native ownership',()=>{
 test('uses admin gate and preserves direct rollback',()=>{assert.match(PAGE,/<AdminAccessGate>/);assert.match(PAGE,/subsection="recommend-test"/);assert.ok(existsSync(join(ROOT,'public','pages','admin','grammar','recommend-test.html')))});
 test('normal navigation uses clean route',()=>{assert.ok(HUB.includes("href: '/admin/grammar/recommend-test'"));assert.match(CHROME,/slug: 'recommend-test'[^\n]+href: '\/admin\/grammar\/recommend-test'/)});
 test('pins no-persistence, edit invalidation, stale-response protection, and production outcomes',()=>{assert.doesNotMatch(CLIENT,/window\.api\.(patch|delete|upload)/);assert.match(CLIENT,/NO PERSISTENCE/);assert.match(CLIENT,/draft_suppressed/);assert.match(CLIENT,/below_threshold/);assert.match(CLIENT,/const editIssue = \(next: string\) => \{ seq\.current \+= 1; setIssue\(next\); setResult\(null\)/);assert.match(CLIENT,/id === seq\.current/);assert.match(LEGACY,/requestId !== runSequence/)});
 test('ships responsive CI ownership',()=>{assert.match(CSS,/@media\(max-width:760px\)/);assert.match(CSS,/@media\(prefers-reduced-motion:reduce\)/);assert.match(LEDGER,/authed-admin-grammar-recommend[^\n]+draft-suppressed/);assert.match(WORKFLOW,/verify-admin-grammar-recommend-flow\.mjs/)});
});
describe('recommendation result contract',()=>{
 test('accepts a canonical matched candidate',()=>{const r=normalizeGrammarRecommendPayload({issue:'x',outcome:'matched',match:c,candidate:c},'x');assert.equal(r.match.url,c.url);assert.equal(formatGrammarMatchScore(.914), '91%')});
 test('keeps below threshold distinct from draft suppression',()=>{assert.equal(normalizeGrammarRecommendPayload({issue:'x',outcome:'below_threshold',match:null,candidate:null},'x').candidate,null);const d={...c,status:'draft'};assert.equal(normalizeGrammarRecommendPayload({issue:'x',outcome:'draft_suppressed',match:null,candidate:d},'x').candidate.status,'draft')});
 test('rejects issue mismatch, contradictory outcomes, and deceptive route prefixes',()=>{assert.equal(normalizeGrammarRecommendPayload({issue:'y',outcome:'matched',match:c,candidate:c},'x'),null);assert.equal(normalizeGrammarRecommendPayload({issue:'x',outcome:'matched',match:null,candidate:c},'x'),null);assert.equal(normalizeGrammarRecommendPayload({issue:'x',outcome:'draft_suppressed',match:null,candidate:c},'x'),null);const deceptive={...c,url:'/grammar/tenses/past-perfect-evil'};assert.equal(normalizeGrammarRecommendPayload({issue:'x',outcome:'matched',match:deceptive,candidate:deceptive},'x'),null)});
});
